config/routes.rb
Rails.application.routes.draw do
  resources :themes
  resources :game_players
  resources :game_objectives
  resources :dices
  resources :money_packs
  resources :strong_hold_cards
  resources :villiage_cards
  resources :heart_shape_herb_cards
  resources :kimoyo_bead_cards
  resources :utility_cards
  resources :transport_cards
  resources :alliances
  resources :title_deed_cards
  resources :character_cards
  resources :tokens
  resources :payments
  resources :onboardings
  resources :accountings
  resources :human_resources
  resources :retentions
  resources :customer_services
  resources :sales
  resources :marketings
  resources :supports
  resources :shippings
  resources :invoices
  resources :billings
  resources :shopping_carts
  resources :games
  resources :streamings
  resources :notifications
  resources :events
  resources :closets
  resources :weathers
  resources :shoppings
  resources :subscriptions
  resources :therapies
  resources :datings
  resources :bankings
  resources :forums
  resources :messages
  resources :user_subscribers
  resources :user_subscribeds
  resources :collections
  resources :favorites
  resources :downloads
  resources :pages
  resources :topics
  resources :categories
  resources :homes
  resources :application_settings
  resources :profiles
  resources :product_pages
  resources :settings
  resources :mailboxes
  resources :dashboards
  resources :posts
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Paypal
resources :payments, only: [:new, :create] do
  collection do
    post :capture
  end
end


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
   root "dashboards#show"

  get 'dashboard/:id', to: 'dashboards#show'
  get 'mailbox/', to: 'mailboxes#index'
  get 'card-dashboard/:id', to: 'dashboards#edit'
  get 'settings', to: 'settings#index'
  get 'payments', to: 'payments#create'
  get 'sign_out', to: "dashboards#sign_out_user"
  get 'profile_edit/:id', to: 'profiles#show'
  #get 'posts', to: 'posts#index'
  #get 'new_post', to: 'posts#new'
  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    can :edit, Profile, user: user
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/banking.rb
class Banking < ApplicationRecord
end

app/models/billing.rb
class Billing < ApplicationRecord
end

app/models/closet.rb
class Closet < ApplicationRecord
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
end

app/models/dating.rb
class Dating < ApplicationRecord
end

app/models/dice.rb
class Dice < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/forum.rb
class Forum < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/models/mailbox.rb
class Mailbox < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
	has_one_attached :post_image

	# Method to return the URL of the attached profile picture
  def post_image_url
    Rails.application.routes.url_helpers.rails_blob_url(post_image, only_path: true) if post_image.attached?
  end
end

app/models/sale.rb
class Sale < ApplicationRecord
end

app/models/theme.rb
class Theme < ApplicationRecord
end

app/models/token.rb
class Token < ApplicationRecord
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :category
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  include UserAssociations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_one_attached :profile_pic
         has_one :dashboard
         has_one :application_setting
         has_many :user_subscribed
         has_many :user_subscriber
         has_many :messages

         # Method to return the URL of the attached profile picture
  def profile_pic_url
    Rails.application.routes.url_helpers.rails_blob_url(profile_pic, only_path: true) if profile_pic.attached?
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: %i[ show edit update destroy ]

  # GET /collections or /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1 or /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections or /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to collection_url(@collection), notice: "Collection was successfully created." }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1 or /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to collection_url(@collection), notice: "Collection was successfully updated." }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1 or /collections/1.json
  def destroy
    @collection.destroy!

    respond_to do |format|
      format.html { redirect_to collections_url, notice: "Collection was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def collection_params
      params.require(:collection).permit(:title, :user_id)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_collection.html.erb
<div id="<%= dom_id collection %>">
  <p>
    <strong>Title:</strong>
    <%= collection.title %>
  </p>

  <p>
    <strong>User:</strong>
    <%= collection.user_id %>
  </p>

</div>

app/views/collections/_form.html.erb
<%= form_with(model: collection) do |form| %>
  <% if collection.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
        <% collection.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<% content_for :title, "Editing collection" %>

<h1>Editing collection</h1>

<%= render "form", collection: @collection %>

<br>

<div>
  <%= link_to "Show this collection", @collection %> |
  <%= link_to "Back to collections", collections_path %>
</div>

app/views/collections/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Collections" %>

<h1>Collections</h1>

<div id="collections">
  <% @collections.each do |collection| %>
    <%= render collection %>
    <p>
      <%= link_to "Show this collection", collection %>
    </p>
  <% end %>
</div>

<%= link_to "New collection", new_collection_path %>

app/views/collections/new.html.erb
<% content_for :title, "New collection" %>

<h1>New collection</h1>

<%= render "form", collection: @collection %>

<br>

<div>
  <%= link_to "Back to collections", collections_path %>
</div>

app/views/collections/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @collection %>

<div>
  <%= link_to "Edit this collection", edit_collection_path(@collection) %> |
  <%= link_to "Back to collections", collections_path %>

  <%= button_to "Destroy this collection", @collection, method: :delete %>
</div>