config/routes.rb
Rails.application.routes.draw do
  resources :themes
  resources :game_players
  resources :game_objectives
  resources :dices
  resources :money_packs
  resources :strong_hold_cards
  resources :villiage_cards
  resources :heart_shape_herb_cards
  resources :kimoyo_bead_cards
  resources :utility_cards
  resources :transport_cards
  resources :alliances
  resources :title_deed_cards
  resources :character_cards
  resources :tokens
  resources :payments
  resources :onboardings
  resources :accountings
  resources :human_resources
  resources :retentions
  resources :customer_services
  resources :sales
  resources :marketings
  resources :supports
  resources :shippings
  resources :invoices
  resources :billings
  resources :shopping_carts
  resources :games
  resources :streamings
  resources :notifications
  resources :events
  resources :closets
  resources :weathers
  resources :shoppings
  resources :subscriptions
  resources :therapies
  resources :datings
  resources :bankings
  resources :forums
  resources :messages
  resources :user_subscribers
  resources :user_subscribeds
  resources :collections
  resources :favorites
  resources :downloads
  resources :pages
  resources :topics
  resources :categories
  resources :homes
  resources :application_settings
  resources :profiles
  resources :product_pages
  resources :settings
  resources :mailboxes
  resources :dashboards
  resources :posts
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Paypal
resources :payments, only: [:new, :create] do
  collection do
    post :capture
  end
end


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
   root "dashboards#show"

  get 'dashboard/:id', to: 'dashboards#show'
  get 'mailbox/', to: 'mailboxes#index'
  get 'card-dashboard/:id', to: 'dashboards#edit'
  get 'settings', to: 'settings#index'
  get 'payments', to: 'payments#create'
  get 'sign_out', to: "dashboards#sign_out_user"
  get 'profile_edit/:id', to: 'profiles#show'
  #get 'posts', to: 'posts#index'
  #get 'new_post', to: 'posts#new'
  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    can :edit, Profile, user: user
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/banking.rb
class Banking < ApplicationRecord
end

app/models/billing.rb
class Billing < ApplicationRecord
end

app/models/closet.rb
class Closet < ApplicationRecord
end

app/models/dating.rb
class Dating < ApplicationRecord
end

app/models/dice.rb
class Dice < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/forum.rb
class Forum < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/models/mailbox.rb
class Mailbox < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
	has_one_attached :post_image

	# Method to return the URL of the attached profile picture
  def post_image_url
    Rails.application.routes.url_helpers.rails_blob_url(post_image, only_path: true) if post_image.attached?
  end
end

app/models/sale.rb
class Sale < ApplicationRecord
end

app/models/theme.rb
class Theme < ApplicationRecord
end

app/models/token.rb
class Token < ApplicationRecord
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :category
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  include UserAssociations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_one_attached :profile_pic
         has_one :dashboard
         has_one :application_setting
         has_many :user_subscribed
         has_many :user_subscriber
         has_many :messages

         # Method to return the URL of the attached profile picture
  def profile_pic_url
    Rails.application.routes.url_helpers.rails_blob_url(profile_pic, only_path: true) if profile_pic.attached?
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /topics or /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1 or /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics or /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully created." }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1 or /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully updated." }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1 or /topics/1.json
  def destroy
    @topic.destroy!

    respond_to do |format|
      format.html { redirect_to topics_url, notice: "Topic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
        @current_user = current_user
      params.permit(:title, :body, :category_id, :user_id,:authenticity_token,:topic, :commit, :Context)
      @cleaned_params = params.permit(:title, :body, :category_id, :user_id)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_with(model: topic) do |form| %>
  <% if topic.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
        <% topic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>
  
  <br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<div id="<%= dom_id topic %>">
  <p>
    <strong>Title:</strong>
    <%= topic.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= topic.body %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= topic.category_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= topic.user_id %>
  </p>

</div>

app/views/topics/edit.html.erb
<% content_for :title, "Editing topic" %>

<h1>Editing topic</h1>

<%= render "form", topic: @topic %>

<br>

<div>
  <%= link_to "Show this topic", @topic %> |
  <%= link_to "Back to topics", topics_path %>
</div>

app/views/topics/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Topics" %>

<h1>Topics</h1>

<div id="topics">
  <% @topics.each do |topic| %>
    <%= topic.title %>
    <p>
      <%= link_to "Show this topic", topic %>
    </p>
  <% end %>
</div>

<div>
<%Topic.all.each do |t|%>
<%=t.title%>
<%end%>
</div>

<%= link_to "New topic", new_topic_path %>

app/views/topics/new.html.erb
<% content_for :title, "New topic" %>

<h1>New topic</h1>

<%= render "form", topic: @topic %>

<br>

<div>
  <%= link_to "Back to topics", topics_path %>
</div>

app/views/topics/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @topic %>

<div>
  <%= link_to "Edit this topic", edit_topic_path(@topic) %> |
  <%= link_to "Back to topics", topics_path %>

  <%= button_to "Destroy this topic", @topic, method: :delete %>
</div>